### ISSUE TITLE
Jira req with template

### ISSUE THREAD

**Issue by vanniktech** [go-jira/jira#177]
I've got the following custom command:

```yml
custom-commands:
  - name: sprint-information
    help: show information of the active sprint for project
    script: |
      board_id=$({{jira}} req "/rest/agile/1.0/board?projectKeyOrId=$JIRA_PROJECT" --gjq values.0.id)
      {{jira}} req "/rest/agile/1.0/board/$board_id/sprint?state=active" --gjq values.0
```

When executing `jira sprint-information` I get the following output:

```json
{
            "endDate": "2018-05-25T13:00:00.000Z",
            "goal": "Some goal",
            "id": 755,
            "name": "Some name",
            "originBoardId": 96,
            "self": "https://foo.atlassian.net/rest/agile/1.0/sprint/755",
            "startDate": "2018-05-07T09:28:28.027Z",
            "state": "active"
        }
```

I would expect that when slamming `--template table` onto it I'd get the json displayed as a nice table.

```diff
-{{jira}} req "/rest/agile/1.0/board/$board_id/sprint?state=active" --gjq values.0
+{{jira}} req "/rest/agile/1.0/board/$board_id/sprint?state=active" --gjq values.0 --template table
```

That's not the case though. I'm still getting the normal JSON printed out. Is there any special configuration I need to do?
