### ISSUE TITLE
How to configure custom/localized transitions 

### ISSUE THREAD

**Issue by dgrabla** [go-jira/jira#294]
I'm using a Jira instance with non-standard transitions:

```
> jira transitions [TICKET]
11: Aufgaben
21: In Arbeit
31: Fertig
41: DEVELOPER DONE
51: TESTING
61: REVIEW
71: Clarification
81: INCIDENCES (CRITICAL)
```

I'm trying to make the shortcuts todo, start, resolve, done etc transition related commands (or aliases?) to use my custom transition names. I tried the following:

```
> jira todo --override="status: Aufgabe" [TICKET] 
> jira todo --resolution="Aufgabe" [TICKET]
```

They both return 
```
ERROR Invalid Transition "To Do" from "In Arbeit", Available: Aufgaben, In Arbeit, Fertig, DEVELOPER DONE, TESTING, REVIEW, Clarification, INCIDENCES (CRITICAL)
```

Using the transition command works
```
> jira transition --noedit "Aufgaben" [TICKET]
OK [TICKET] https://tignum.atlassian.net/browse/[TICKET]
```

I exported the templates but... no todo template is exported.
 
What should I have on the config.yml to default the todo command to "Aufgaben" instead of "To Do"?

**Comment by svenXY** [comment]
I agree that it should help non-English version users a lot to be able to set these statuses if they are not standard.

Furthermore, being able to set something yourself (=overwrite) is a feature that could also help with the problems arising from the usage of customfields for standard things like e.g. watchers (see #304 as an example)

**Comment by coryb** [comment]
Would [custom commands](https://github.com/go-jira/jira#custom-commands) work here instead of modifying what `todo` means?  You can make a local language alias:
```
custom-commands:
  - name: aufgaben
    help: transition issue to aufgaben
    args:
      - name: ISSUE
        required: true
    script: |
      jira transition --noedit aufgaben {{args.ISSUE}}
```
Then you can use it like `jira aufgaben JIRA-123`
