### ISSUE TITLE
args and options shared between custom commands

### ISSUE THREAD

**Issue by Flare576** [go-jira/jira#307]
Situation: I have a lot of custom commands, some of which share argument and option names.
Problem: If one of my commands `defaults` the value of an argument, ALL of the commands using that argument name get defaulted. In addition, it seems that any args from other functions also bleed
Expected: Each command's arguments/options be siloed

Example: 
> .jira.d/config.yml
```
#!/bin/bash
cat<<END
custom-commands:
  - name: cmd1
    args:
      - name: FOO
    script: |-
      echo "I have a FOO arg: {{args.FOO}}"
  - name: cmd2
    args:
      - name: FOO
        default: "BAR"
    script: |-
      echo "I have a FOO arg defaulted to BAR: {{args.FOO}}"
END
```

running the "cmd1" command with no input shows it defaulting to `BAR` and also having access to the UNICORN argument from cmd2.

Basic Info:
```
 ~ > brew info go-jira
go-jira: stable 1.0.22 (bottled)
Simple jira command-line client in Go
https://github.com/go-jira/jira
/usr/local/Cellar/go-jira/1.0.22 (6 files, 10MB) *
  Poured from bottle on 2019-10-16 at 16:39:31
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/go-jira.rb
==> Dependencies
Build: go ✘
==> Analytics
install: 108 (30 days), 553 (90 days), 2,171 (365 days)
install-on-request: 108 (30 days), 551 (90 days), 2,162 (365 days)
build-error: 0 (30 days)
```
