### ISSUE TITLE
Browse does not respect project in config

### ISSUE THREAD

**Issue by matt-canty-dragon** [go-jira/jira#339]
## Setup
In `.jira.d/config.yml`
```
project: ABC
```

## What Happens
```
➜  ~ j browse 391
WARNING Using abbreviated issue "391" but `project` property is not defined
```
Address in browser is https://mydomain.atlassian.net/browse/391

## What I Expect
Address in browser to be https://mydomain.atlassian.net/browse/ABC-391

## Thoughts
Looks like [browse.go](https://github.com/go-jira/jira/blob/b590005aac15da9060135c178504df1cde106c0a/jiracmd/browse.go) is missing [assignment of default value](https://github.com/go-jira/jira/blob/417568ca2daf474e8e81643a291dd51fc2446d36/jiracmd/create.go) from config.
```
cmd.Flag("project", "project to create issue in").Short('p').StringVar(&opts.Project)
```

**Comment by matt-canty-dragon** [comment]
I created a custom command to get around this issue.

```yaml
  - name: open
    help: Opens the issue in the default browser
    args:
      - name: ISSUE
        help: issue id to view
        required: true
    script: |-
      ISSUE={{ args.ISSUE }}
      re='^[0-9]+$'
      if [[ $ISSUE =~ $re ]] ; then
        ISSUE=$JIRA_PROJECT-$ISSUE
      fi

      open $JIRA_ENDPOINT/browse/$ISSUE
```
