### ISSUE TITLE
Flow broken due to username/GDPR issue

### ISSUE THREAD

**Issue by matt-canty-dragon** [go-jira/jira#344]
I cannot use go-jira at the moment. My flow is to create issues with `jira create` then use `jira take` and `jira in-progress`.

However as I have been getting this error for a few weeks now I have slowly stopped using it.

```
ERROR Invalid Usage: The query parameter 'username' is not supported in GDPR strict mode.
```

https://github.com/go-jira/jira/issues/333#issuecomment-631077242 this issue only goes so far as fixing the create aspect. But once a ticket is created it also cannot be managed beyond that point. 

I think #343 gets part of the way there, but really a complete switch from username for both assignee and reporter is required. I think also that this is probably a change here... https://github.com/go-jira/jira/blob/417568ca2daf474e8e81643a291dd51fc2446d36/jiracmd/assign.go#L64

**Comment by belambic** [comment]
I'm having the same issue, `jira take` just doesn't work any more.

**Comment by erik-niehaus** [comment]
Same. Jira create is patch-able with #333, but `jira take` is not functional.

**Comment by matt-canty-dragon** [comment]
I gave up a little in order to get the functionality back. I use a custom command `work-on` and have used `curl` to hack the assignment to me.

The use of Regex just keeps this command in line with all the other commands by prefixing the project ID if needed.

```yaml
assignee: stub # your profile ID
api-key: stub # your API key

custom-commands:
  - name: work-on
    help: Assigns issue and moves to in-progress
    aliases:
      - wo
    args:
      - name: ISSUE
        help: issue id to work on
        required: true
    script: |-
      ISSUE={{ args.ISSUE }}
      re='^[0-9]+$'
      if [[ $ISSUE =~ $re ]] ; then
        ISSUE=$JIRA_PROJECT-$ISSUE
      fi

      jira in-progress $ISSUE

      curl --request PUT \
        --url https://projectdrgn.atlassian.net/rest/api/3/issue/$ISSUE/assignee \
        --data '{"accountId":"'$JIRA_ASSIGNEE'"}' \
        --header 'Accept: application/json' \
        --header 'Content-Type: application/json' \
        --user $JIRA_USER':'$JIRA_API_KEY
```

I found the following helpful:

```yaml
custom-commands:
  - name: printenv
    help: Prints environment variables
    script: printenv
```
