### ISSUE TITLE
Supporting linking to pull request

### ISSUE THREAD

**Issue by ldelossa** [go-jira/jira#361]
As part of our jira workflow we have a transition step which requires a link to a pull request.

When I use the transition command in jira I'm presented a buffer for submission:

```
fields:
  transition:
    id: 711
    name: Link Pull Request
```

am I able to provide a pull request link in this yaml?
