### ISSUE TITLE
ERROR reporter: Reporter is required.

### ISSUE THREAD

**Issue by wkoszek** [go-jira/jira#369]
I just fetched the latest revision a1450e879f62be6faaa6cc518521859837ea084f and built it with "make"

I have:

```
endpoint: https://mywrkspace.atlassian.net
user: adam@mycompany.com
password-source: keyring
```

API overall works, e.g.: `jira ls` shows me the tickets fine. I'm attempting to create a ticket in a "backend" project with "BE":

```
jira create --project BE
```

I get dropped to Vim and make a dummy ticket:

```
fields:
  project:
    key: BE
  issuetype:
    name: Bug
  summary: >-
    sample 
  priority: # Values: Highest, High, Medium, Low, Lowest, 
    name: High
  description: |~
    sample
  assignee:
    name: adam@mycompany.com
  reporter:
    name: adam@mycompany.com
```

Error I get:

```
ERROR reporter: Reporter is required.
? Jira reported an error, edit again? Yes
```

Regardless of what I try to put in "reporter" field, I get this error. Should the `jira create` template just work fine? I read README about JIRA username vs login issues and G and also attempted to add:

```
user: adam
login: adam@mycompany.com
```

And I tried following formats in the "reporter":
- adam
- adam@mycompany.com
- "W. Adam Koszek"

Nothing worked. Any hints?
