### ISSUE TITLE
Can't set "Assignee" during ticket creation

### ISSUE THREAD

**Issue by wkoszek** [go-jira/jira#378]
I'm solving https://github.com/go-jira/jira/issues/369 issue by removing the "reporter" field. Creating issues works that way, however I can't set the "assignee" field. I tried "wkoszek", "wkoszek@mycompany.ai", "W. Adam Koszek".

The way to reproduce:

```
/Users/wk/r_other/jira/jira create --project BE
```

Template I'm trying out:

```
fields:
  project:
    key: BE
  issuetype:
    name: Bug
  summary: >-
    sample
  priority: # Values: Highest, High, Medium, Low, Lowest,
    name:
  description: |~
     sample

  assignee:
    name: wkoszek@mycompany.ai
```

Looks like the ticket is created OK, but the assignee isn't set.
