### ISSUE TITLE
How to list custom commands and their respective help message?

### ISSUE THREAD

**Issue by jason-riddle** [go-jira/jira#393]
It would be nice to run a command say `list_custom_commands` and given

`config.yml`

```yml
custom-commands:
  - name: env
    help: Print the JIRA environment variables available to custom commands
    script: |
      ...
  - name: mine
    help: Show stories assigned to me
    script: |-
      ...
```

it might output

```
jira list_custom_commands

env:   Print the JIRA environment variables available to custom commands
mine:  Show stories assigned to me
```

Is this currently possible?
